# vim ft=yaml
# travis-ci.org definition for testkraut build (based on the PyMVPA
# configuration that is based on the nipype configuration which in turn was
# based on nipy)
#
# We pretend to be erlang because we need can't use the python support in
# travis-ci; it uses virtualenvs, they do not have numpy, scipy, matplotlib,
# and it is impractical to build them
language: erlang
env:
    - PYTHON=python PYSUF=''
    # - PYTHON=python3 PYSUF=3 : python3-numpy not currently available
install:
    - sudo rmdir /dev/shm
    - sudo ln -Tsf /{run,dev}/shm
    - sudo apt-get update -qq
    - sudo apt-get install lsb-release
    - source /etc/lsb-release
    - echo ${DISTRIB_CODENAME}
    - wget -O- http://neuro.debian.net/lists/${DISTRIB_CODENAME}.de-md.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
    - sudo apt-key adv --recv-keys --keyserver pgp.mit.edu 2649A5A9
    - sudo apt-get update -qq
    #- sudo apt-get install $PYTHON-dev
    - sudo apt-get install -qq $PYTHON-numpy
    - sudo apt-get install -qq $PYTHON-scipy
    - sudo apt-get install -qq $PYTHON-nibabel
    - sudo apt-get install -qq $PYTHON-nose
    - sudo apt-get install -qq $PYTHON-pydot
    - sudo apt-get install -qq $PYTHON-testtools
    - sudo apt-get install -qq $PYTHON-nipype
    - sudo apt-get install -qq strace
script:
    - ls -l
    - $PYTHON -c 'from testkraut import cfg; print cfg'
    # Run only nonlabile tests
    - TESTKRAUT_TESTRUN_SKIP_DEPENDENCY_DESCRIPTION=yes make test
